export const GET_NOTES_FOR_DATE_REQUESTED = 'GET_NOTES_FOR_DATE_REQUESTED';
export const GET_NOTES_FOR_DATE_SUCCESS = 'GET_NOTES_FOR_DATE_SUCCESS';
export const SEARCH_NOTES_BY_CONTENT = 'SEARCH_NOTES_BY_CONTENT';
export const POST_NOTES = 'POST_NOTES';
export const NOTES_ERROR = 'NOTES_ERROR';
